In [4]:
from PIL import Image
import numpy as np


img_filename = "data/lfw/Aaron_Eckhart/Aaron_Eckhart_0001.jpg"
color_img = np.asarray(Image.open(img_filename)) / 255

In [5]:
print(color_img)

[[[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  ...
  [0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.         0.         0.        ]]

 [[0.         0.         0.        ]
  [0.         0.         0.        ]
  [0.00392157 0.00392157 0.00392157]
  ...
  [0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]
  [0.01176471 0.01176471 0.01176471]]

 ...

 [[0.41176471 0.4745098  0.57647059]
  [0.43529412 0.49803922 0.6       ]
  [0.46666667 0.5254902  0.63921569]
  ...
  [0.47058824 0.51372549 0.59215686]
  [0.52156863 0.56470588 0.64313725]
  [0.54901961 0.59215686 0.67058824]]

 [[0.40784314 0.47058824 0.57254902]
  [0.41568627 0.47843137 0.58039216]
